export const NICKNAMES = [
    'Roach',
    'Broken',
    'Dogtag',
    'Rat',
    'Mother',
    'Lucky',
    'Jerky',
    'Target',
    'Lover',
    'Noisy',
    'Killer',
    'Tiny',
    'Ballerina',
    'Scar',
    'Runner',
    'Speedball',
    'High and Tight',
    'Gunner',
    'Che',
    'Sisu',
    'Tooth',
    'Grit',
    'Nothing',
    'Writer',
    'Sib',
    'Jackass',
    'Slim',
    'Lazy',
    'Havi',
    'Narrow',
    'Tallow',
    'Gear',
    'Steamer',
    'Nothing',
    'Gore',
    'Rat',
    'Leak',
    'Tack',
    'Slaggy',
    'Maker',
    'Boom-Boom',
    'Soup',
    'Bones',
    'Old Dog',
    'Pest',
    'Squeak',
    'Nightlife',
    'Tower',
    'Toothless',
    'Cy',
    'Snow',
    'Monster',
    'Face',
    'Foreigner',
    'Thumper',
    'Drip',
    'Sarkash',
    'Meat',
    'Sticky',
    'Pusher',
    'Gritty',
    'Solo',
    'Hybrid',
    'Brain',
    'Buster',
    'Cruise',
    'Thief',
    'Gorgon',
    'Yo',
    'Stab',
    'Bark',
    'Chunk',
    'Nobody',
    'Retch',
    'Doom',
    'Pinky',
    'Flash',
    'Mark',
    'Frost',
    'Milky',
    'Boing-Boing',
    'Knot',
    'Crusher',
    'Moth',
    'Player',
    'Bear',
    'Johnny',
    'Flush',
    'Cleaner',
    'Lip',
    'Nope',
    'Drag',
    'Drug',
    'Pop',
    'Eraser',
    'Moonchild',
    'Smiles',
    'Dragline',
    'Ender',
    'Borg',
];

export const REASONS = [
    'because you had no choice - it was that, or be <strong>hung for your crimes</strong>',
    'because as a prisoner you developed an obsession with <span class="emphasize">BRUTALITY AND PAIN</span>',
    'for the greater good of your <strong>god</strong>',
    'because killing is your business, & business is <strong>good</strong>',
    'because you were <strong>exiled from your village</strong> and had no where else to go.',
    'due to your desire for wanton, bloody, terrifying <strong>hedonism</strong>',
    'because an incurable disease ails you - <strong>you are not long for this world anyway</strong>',
    'to feed your <strong>addiction</strong> to the roar of flames and blasts of shrapnel',
    'because you are <strong>seduced</strong> by the morose',
    'because your <strong>mother signed you up</strong> - you\'re the eldest after all',
    'because you struggle with a ghastly addiction to the <strong>taste of blood</strong>',
    'because you seek the <strong>honor</strong> to be buried among the <strong>flowers in Newfield</strong>',
    'because your <strong>farmstead</strong> was destroyed and your <strong>family killed</strong>',
    'to eat - <strong>starvation</strong> is a great motivator. They feed grvnts...<strong>mostly</strong>',
    'due to a misguided sense of <strong>justice</strong>',
    'because the land changed, wiping out your way of life. <strong>You have nothing to go back to</strong>',
    'because your <strong>lover</strong> is fighting on the other side. You want to be close to them - <strong>at a bayonet\'s length</strong>',
    'for some reason, but you <strong>don\'t remember it</strong>',
    '<strong>FOR GLORY!</strong> (Your corpse will be stepped on)',
    'after rising from the <strong>dead</strong>, resuming your past life'
];
