export const NICKNAMES = [
    'Roach',
    'Broken',
    'Dogtag',
    'Rat',
    'Mother',
    'Lucky',
    'Jerky',
    'Target',
    'Lover',
    'Noisy',
    'Killer',
    'Tiny',
    'Ballerina',
    'Scar',
    'Runner',
    'Speedball',
    'High and Tight',
    'Gunner',
    'Che',
    'Sisu',
    'Tooth',
    'Grit',
    'Nothing',
    'Writer',
    'Sib',
    'Jackass',
    'Slim',
    'Lazy',
    'Havi',
    'Narrow',
    'Tallow',
    'Gear',
    'Steamer',
    'Nothing',
    'Gore',
    'Rat',
    'Leak',
    'Tack',
    'Slaggy',
    'Maker',
    'Boom-Boom',
    'Soup',
    'Bones',
    'Old Dog',
    'Pest',
    'Squeak',
    'Nightlife',
    'Tower',
    'Toothless',
    'Cy',
    'Snow',
    'Monster',
    'Face',
    'Foreigner',
    'Thumper',
    'Drip',
    'Sarkash',
    'Meat',
    'Sticky',
    'Pusher',
    'Gritty',
    'Solo',
    'Hybrid',
    'Brain',
    'Buster',
    'Cruise',
    'Thief',
    'Gorgon',
    'Yo',
    'Stab',
    'Bark',
    'Chunk',
    'Nobody',
    'Retch',
    'Doom',
    'Pinky',
    'Flash',
    'Mark',
    'Frost',
    'Milky',
    'Boing-Boing',
    'Knot',
    'Crusher',
    'Moth',
    'Player',
    'Bear',
    'Johnny',
    'Flush',
    'Cleaner',
    'Lip',
    'Nope',
    'Drag',
    'Drug',
    'Pop',
    'Eraser',
    'Moonchild',
    'Smiles',
    'Dragline',
    'Ender',
    'Borg',
];

export const REASONS = [
    'because you had no choice - it was that, or be <strong>hung for your crimes</strong>',
    'because as a prisoner you developed an obsession with <span class="emphasize">BRUTALITY AND PAIN</span>',
    'for the greater good of your <strong>god</strong>',
    'because killing is your business, & business is <strong>good</strong>',
    'because you were <strong>exiled from your village</strong> and had no where else to go.',
    'due to your desire for wanton, bloody, terrifying <strong>hedonism</strong>',
    'because an incurable disease ails you - <strong>you are not long for this world anyway</strong>',
    'to feed your <strong>addiction</strong> to the roar of flames and blasts of shrapnel',
    'because you are <strong>seduced</strong> by the morose',
    'because your <strong>mother signed you up</strong> - you\'re the eldest after all',
    'because you struggle with a ghastly addiction to the <strong>taste of blood</strong>',
    'because you seek the <strong>honor</strong> to be buried among the <strong>flowers in Newfield</strong>',
    'because your <strong>farmstead</strong> was destroyed and your <strong>family killed</strong>',
    'to eat - <strong>starvation</strong> is a great motivator. They feed grvnts...<strong>mostly</strong>',
    'due to a misguided sense of <strong>justice</strong>',
    'because the land changed, wiping out your way of life. <strong>You have nothing to go back to</strong>',
    'because your <strong>lover</strong> is fighting on the other side. You want to be close to them - <strong>at a bayonet\'s length</strong>',
    'for some reason, but you <strong>don\'t remember it</strong>',
    '<strong>FOR GLORY!</strong> (Your corpse will be stepped on)',
    'after rising from the <strong>dead</strong>, resuming your past life'
];

export const SCARS = [
    'crooked <strong>facial scar</strong>, stuffed with horsehair',
    'infected finger on your <strong>left hand</strong>',
    'infected finger on your <strong>right hand</strong>',
    '<strong>burnt eye</strong> with flaking skin and a pungent smell',
    'constant concussion, making you <strong>prone to headaches</strong>',
    'nose replaced by a <strong>gash</strong>',
    'razor wire embedded in your arm (d6)',
    'shortened stride from a <strong>Shinripper</strong>. You tread lightly ever since.',
    'permanent <strong>thousand-league</strong> stare',
    'small piece of <strong>sharpnel</strong> that painfully migrates through your body',
    '[d6] <strong>missing teeth</strong>',
    'broken blood vessel in your <strong>right eye</strong>',
    'broken blood vessel in your <strong>left eye</strong>',
    'a single <strong>fractured rib</strong> that rattle as you run',
    'a pair of <strong>fractured ribs</strong> that rattle as you run',
    'weak knees and a hunched posture, making you a <strong>smaller target</strong>',
    'massive, distracting <strong>hematoma</strong>',
    '<strong>Slaggvara</strong> shrapnel protruding from your head like a <strong>demon horn</strong>, promising certain death if removed',
    '<strong>gas-mask</strong> melted to your face - <strong>still works</strong>',
    'crudely <strong>severed hand</strong>',
    'hole in the side of your mouth, <strong>exposing teeth</strong>',
    'stab wound that <strong>never heals</strong>, stuffed with gauze',
    'severe case of <strong>battle tinnitus</strong> that <strong>blocks out everything</strong> else when in shock',
    'disfiguration from <strong>Dark Thoughts</strong>; you don\'t like talking about it',
    '<strong>terminal cough</strong>...small puffs of <strong>gas</strong> hacked up from time to time',
    '<strong>ripped throat</strong> from an attempted assassination',
    'bite mark from <strong>something human</strong>',
    '<strong>flayed scalp</strong>, dangles in the wind',
    '<strong>snaggletooth</strong> punctured through your lip',
    'arrow loged in your <strong>femoral artery</strong>, tickes to the touch',
    '<strong>broken foot</strong>, crushed by iron treads',
    '<strong>Slaggvara tattoo</strong>, won\'t stop itching',
    '<strong>shoulder</strong> that pops out of place at will',
    'criss-cross of <strong>deep rope burns</strong> on your palms',
    '<strong>hole in your skull</strong> that causes helmets to never fit right',
    'severe contusion that looks <strong>oddly like a face</strong>',
    'set of soggy, <strong>necrotic toes</strong>',
    '<strong>lacerated arm</strong>, probably needs treatment',
    '<strong>slow leaking abscess</strong>, smells terribly of offal'
];

export const VICES = [
    'fondling a <strong>Shinripper</strong>',
    'confessing <strong>war crimes</strong> to the cynically cursed chaplain',
    'burning through an <strong>entire pack of smokes</strong> in a night',
    'writing horrible poetry (and forcing otheres to <strong>listen to it</strong>)',
    'holding your hand above flames until the <strong>pain</strong> is too great',
    'placing bets with your fellow <strong>grvnts</strong>',
    '<strong>endlessly</strong> counting ammunition',
    'reading the names on every dog tag you\'ve collected (<strong>you must have more</strong>)',
    'walking among the corpses, looking for a <strong>familiar face</strong>',
    'biting your <strong>fingernails</strong> way too short',
    'creating <strong>morose paints</strong> of the day\'s atrocities',
    'juggling <strong>grenades</strong> - the more, the better',
    'overindulging in drink until <strong>passing out</strong>',
    'meticulously and eerily <strong>cleaning weapons</strong>',
    'donning a <strong>gas-mask</strong> for no reason',
    'snorting crushed <strong>slagg</strong>',
    'writing letters to <strong>no one</strong>',
    'dry shaving with a jagged, rusty <strong>bayonet</strong>',
    'carving <strong>useless</strong> wooden crosses',
    'cataloging every <strong>injury</strong> in your diary',
];
